# Generated by Django 6.0.5 on 2026-05-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_gameresult_options_gameresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='player_color',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black')], default='white', max_length=5),
        ),
    ]
